name: Daily Status Script

on:
  schedule:
    # Runs every day at 9:00 AM GMT+5:30 (which is 3:30 AM UTC)
    - cron: '30 3 * * *'

  workflow_dispatch:

jobs:
  run-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run status script
        run: python status.py
        env:
          APP_PASSWORD: ${{ secrets.APP_PASS }}  # GitHub Secret




