name: Daily Status Script

on:
  schedule:
    # Runs every day at 10:00 AM GMT+5:30 (which is 4:30 AM UTC)
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests  # ✅ Installs the 'requests' package

      - name: Run status script
        run: python status.py
        env:
          APP_PASSWORD: ${{ secrets.APP_PASS }}  # ✅ Loads your GitHub Secret



